### PR TITLE
Adding helpers in options

### PR DESCRIPTION
**Pull request by jun68ykt**
Hello.

 Thank you for your mock-api-middleware. It's very useful for developing web frontends including restful APIs responding with JSON.  

 I hope that the MOM can receive customized helpers which are described in the dummy-json documents "[writing-your-own-helpers](https://github.com/webroo/dummy-json#writing-your-own-helpers)" through the [options](https://www.npmjs.com/package/mock-api-middleware#options) passed on initialization of MAM.

So I sent this PR which includes adding `helpers` to the 2nd parameter object for `dummyjson.parse()`. By this, we can write the code like following:

```javascript
const mam = require('mock-api-middleware');
const myHelpers = require('./src/myHelpers');

const mockApi = mam('/api', { // <--- Route where to mount the API
    mockPath: './mock_api/', // <--- Where to find the API files
    helpers: myHelpers,
});
```
`myHelpers.js` is like following
```javascript
module.exports = {
  direction: function() {
    // Use dummyjson random to ensure the seeded random number generator is used
    return dummyjson.utils.random() > 0.5 ? 'left' : 'right';
  }
};
```
This `direction` function above enable us to write 

`{{direction}}`

in the MAM jsons and it will become a string of `left` or  `right` in API responses.

Best regards.

### CODE REVIEW

**Comment by Saturate** [comment]
Thanks for your contribution @jun68ykt! I will take a look at it, and get it merged.
Looks super helpful.

I'm very happy that you find it useful! Here I was thinking that I was the only one using it on some projects for testing things.

**Review by Saturate — APPROVED** [review]

**Comment by jun68ykt** [comment]
@Saturate 
Thank you for your merging my PR !
I use MAM very often in the project in which I engage now. Thanks.

**Comment by Saturate** [comment]
I'm the one that thanks for the PR :-)

Sounds exiting! Glad you can use it. Let me know if you need any features, or have problems.

Pushed the new version to NPM.

**Comment by jun68ykt** [comment]
I got it !

**Pull request merged**
